"""Administration commands for the ignored local runtime tree."""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path

from solar_apps.platform.layout import RuntimeLayout
from solar_apps.platform.migration import migrate_legacy_state

_SHIM = r"""# Generated by `solar_apps admin init`; this file stays in ignored Local/.
$ErrorActionPreference = "Stop"
$workspaceRoot = Split-Path -Parent $PSScriptRoot
$launcher = Join-Path $workspaceRoot "Apps\run.ps1"
& $launcher @args
exit $LASTEXITCODE
"""


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="Apps/run.ps1 admin",
        description="Initialize the private Local runtime tree.",
    )
    commands = parser.add_subparsers(dest="command", required=True)
    initialize = commands.add_parser("init", help="Create Local runtime directories.")
    initialize.add_argument(
        "--force-config",
        action="store_true",
        help="Replace paths.local.yaml with the public empty-root template.",
    )
    return parser


def initialize_runtime(
    *,
    layout: RuntimeLayout | None = None,
    force_config: bool = False,
) -> tuple[Path, ...]:
    """Create runtime directories, a safe config, and the compatibility shim."""

    selected = (layout or RuntimeLayout.discover()).ensure()
    template = selected.apps_root / "configs" / "examples" / "paths.example.yaml"
    if not template.is_file():
        raise FileNotFoundError(f"Application config template is missing: {template}")
    created: list[Path] = []
    if not force_config:
        created.extend(migrate_legacy_state(layout=selected))
    if force_config or not selected.config_path.exists():
        shutil.copyfile(template, selected.config_path)
        created.append(selected.config_path)
    shim = selected.local_root / "run.ps1"
    if not shim.exists() or shim.read_text(encoding="utf-8-sig") != _SHIM:
        shim.write_text(_SHIM, encoding="utf-8", newline="\n")
        created.append(shim)
    return tuple(created)


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        if args.command == "init":
            created = initialize_runtime(force_config=args.force_config)
        else:  # pragma: no cover - argparse guards this branch
            parser.error(f"Unknown admin command: {args.command}")
            return 2
    except OSError as exc:
        parser.exit(2, f"admin: error: {exc}\n")
    if created:
        print("Initialized Local runtime files:")
        for path in created:
            print(f"  {path}")
    else:
        print("Local runtime is already initialized.")
    return 0


__all__ = ["build_parser", "initialize_runtime", "main"]
